name: user_repository
description: "project package to manage user"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.4
  equatable: ^2.0.5
  firebase_auth: ^4.17.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
